### ISSUE TITLE
Reintegrate https://github.com/kennylevinsen/mdns-repeater

### ISSUE THREAD

**Issue by kennylevinsen** [geekman/mdns-repeater-hg#3]
Many years back [I forked mdns-repeater](https://github.com/kennylevinsen/mdns-repeater) to add a subnet blacklist/whitelist feature, and I hosted it on my own account to avoid mercurial which I was unfamiliar withat the time. Since then a number of fixes has accumulated. This causes some confusion, and credit is wrongly attributed to me.

I propose integrating the fixes and changes from my version back into yours, and then I'd archive my version and add a link to here. Due to being separate mercurial-to-git conversions it'll take a little manual work, but I can take care of that and create a PR with the changes if you're up for it.

**Comment by geekman** [comment]
Thank you, I'd appreciate that. 🙏 When Bitbucket decided to kill off Mercurial support, I converted the repo to Git and moved it here instead.

>I propose integrating the fixes and changes from my version back into yours, and then I'd archive my version and add a link to here. Due to being separate mercurial-to-git conversions it'll take a little manual work, but I can take care of that and create a PR with the changes if you're up for it.

By doing so, would the current history and the work you've done be lost? I can see there's also various forks that have already been based on your repo.

If I may, might I suggest a transfer instead? This would preserve everything you have done so far, including the issues filed & closed. And this would also avoid you having to reconcile the repos, since this repo is essentially whatever you had at the start anyway when you moved it to Git.

**Comment by kennylevinsen** [comment]
> If I may, might I suggest a transfer instead?

I have no opposition to this, and it does indeed have some Github community related benefits.

Note that in order to initiate a transfer, we would first have to rename or remove this repository due to the name clash. See https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository for prerequisites.

**Comment by geekman** [comment]
The repository has been renamed. I'd probably keep it around for a while longer before removing it completely.

**Comment by kennylevinsen** [comment]
Transfer initiated. You should have an email from Github with information on how to proceed.

**Comment by geekman** [comment]
The transfer is done. Thanks!

If you'd like, please stay on the project as a collaborator. It looks like you've done a far better job than I could have.

**Comment by kennylevinsen** [comment]
Hah, what little I did does not deserve much flatter. I can be re-added as collaborator, but I cannot guarantee how active I will be.

(Closing this issue as migration is complete.)
